#!/usr/bin/env python3
"""Generate img_app_print.c: 112x112 LV_IMG_CF_TRUE_COLOR_ALPHA, rounded corners, trim white margins."""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image, ImageChops, ImageDraw, ImageFilter
except ImportError:
    print("Pillow required: pip install Pillow", file=sys.stderr)
    sys.exit(1)

W = H = 112
CORNER_RADIUS = 22
# Pixels at least this bright (RGB) are treated as border/background for trimming.
WHITE_TRIM_MIN = 248


def rgb_to_lv8(r: int, g: int, b: int) -> int:
    blue2 = (b >> 6) & 0x03
    green3 = (g >> 5) & 0x07
    red3 = (r >> 5) & 0x07
    return blue2 | (green3 << 2) | (red3 << 5)


def rgb_to_lv16(r: int, g: int, b: int) -> int:
    b5 = (b >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    r5 = (r >> 3) & 0x1F
    return b5 | (g6 << 5) | (r5 << 11)


def emit_rows(bytes_list: list[int], first_line_comment: str) -> list[str]:
    lines: list[str] = []
    n = len(bytes_list)
    i = 0
    while i < n:
        chunk = bytes_list[i : i + 16]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        if i == 0 and first_line_comment:
            lines.append(f"  /*{first_line_comment}*/\n  {hexes},")
        else:
            lines.append(f"  {hexes},")
        i += 16
    return lines


def trim_near_white_border(im: Image.Image) -> Image.Image:
    """Remove margins where pixels are near-white (or low-alpha treated as empty)."""
    im = im.convert("RGBA")
    w, h = im.size
    px = im.load()

    def is_border_pixel(x: int, y: int) -> bool:
        r, g, b, a = px[x, y]
        if a < 12:
            return True
        return r >= WHITE_TRIM_MIN and g >= WHITE_TRIM_MIN and b >= WHITE_TRIM_MIN

    min_x, min_y = w, h
    max_x, max_y = -1, -1
    for y in range(h):
        for x in range(w):
            if not is_border_pixel(x, y):
                min_x = min(min_x, x)
                min_y = min(min_y, y)
                max_x = max(max_x, x)
                max_y = max(max_y, y)

    if max_x < min_x or max_y < min_y:
        return im
    pad = 1
    min_x = max(0, min_x - pad)
    min_y = max(0, min_y - pad)
    max_x = min(w - 1, max_x + pad)
    max_y = min(h - 1, max_y + pad)
    return im.crop((min_x, min_y, max_x + 1, max_y + 1))


def resize_cover_center(im: Image.Image, size: int) -> Image.Image:
    """Scale so the image covers size×size, then center-crop."""
    tw, th = im.size
    if tw <= 0 or th <= 0:
        return Image.new("RGBA", (size, size), (0, 0, 0, 0))
    scale = max(size / tw, size / th)
    nw = max(1, int(round(tw * scale)))
    nh = max(1, int(round(th * scale)))
    im = im.resize((nw, nh), Image.Resampling.LANCZOS)
    left = (nw - size) // 2
    top = (nh - size) // 2
    return im.crop((left, top, left + size, top + size))


def apply_rounded_alpha(im: Image.Image) -> Image.Image:
    im = im.convert("RGBA")
    w, h = im.size
    r = min(CORNER_RADIUS, w // 2, h // 2)
    mask = Image.new("L", (w, h), 0)
    draw = ImageDraw.Draw(mask)
    draw.rounded_rectangle((0, 0, w - 1, h - 1), radius=r, fill=255)
    mask = mask.filter(ImageFilter.MinFilter(3))

    rc, gc, bc, ac = im.split()
    new_a = ImageChops.multiply(ac, mask)
    return Image.merge("RGBA", (rc, gc, bc, new_a))


def find_source_png(assets_dir: Path) -> Path:
    for name in ("img_app_print.png", "print.png"):
        p = assets_dir / name
        if p.is_file():
            return p
    raise FileNotFoundError(f"No img_app_print.png or print.png in {assets_dir}")


def main() -> None:
    root = Path(__file__).resolve().parent
    png = find_source_png(root)
    out = root / "img_app_print.c"

    im = Image.open(png)
    im = trim_near_white_border(im)
    im = resize_cover_center(im, W)
    im = apply_rounded_alpha(im)

    px = list(im.convert("RGBA").getdata())

    d8: list[int] = []
    d16: list[int] = []
    d16s: list[int] = []
    d32: list[int] = []
    for r, g, b, a in px:
        d8.extend([rgb_to_lv8(r, g, b), a])
        v = rgb_to_lv16(r, g, b)
        lo, hi = v & 0xFF, (v >> 8) & 0xFF
        d16.extend([lo, hi, a])
        vs = ((v & 0xFF) << 8) | (v >> 8)
        lo2, hi2 = vs & 0xFF, (vs >> 8) & 0xFF
        d16s.extend([lo2, hi2, a])
        d32.extend([b & 0xFF, g & 0xFF, r & 0xFF, a & 0xFF])

    parts: list[str] = []
    parts.append(
        "/* SPDX-License-Identifier: Apache-2.0 */\n"
        f"/* Generated by gen_img_app_print.py from {png.name} */\n\n"
        r"""#ifdef __has_include
    #if __has_include("lvgl.h")
        #ifndef LV_LVGL_H_INCLUDE_SIMPLE
            #define LV_LVGL_H_INCLUDE_SIMPLE
        #endif
    #endif
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
    #include "lvgl.h"
#else
    #include "lvgl/lvgl.h"
#endif


#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_IMG_APP_PRINT
#define LV_ATTRIBUTE_IMG_IMG_APP_PRINT
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_IMG_APP_PRINT uint8_t img_app_print_map[] = {
"""
    )

    parts.append("#if LV_COLOR_DEPTH == 1 || LV_COLOR_DEPTH == 8\n")
    parts.append("  /*Pixel format: Alpha 8 bit, Red: 3 bit, Green: 3 bit, Blue: 2 bit*/\n")
    parts.extend(l + "\n" for l in emit_rows(d8, "112x112 print launcher icon"))
    parts.append("#endif\n")

    parts.append("#if LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP == 0\n")
    parts.append("  /*Pixel format: Alpha 8 bit, Red: 5 bit, Green: 6 bit, Blue: 5 bit*/\n")
    parts.extend(l + "\n" for l in emit_rows(d16, "112x112 print"))
    parts.append("#endif\n")

    parts.append("#if LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP != 0\n")
    parts.append(
        "  /*Pixel format: Alpha 8 bit, Red: 5 bit, Green: 6 bit, Blue: 5 bit  BUT the 2  color bytes are swapped*/\n"
    )
    parts.extend(l + "\n" for l in emit_rows(d16s, ""))
    parts.append("#endif\n")

    parts.append("#if LV_COLOR_DEPTH == 32\n")
    parts.append("  /*Pixel format: Alpha 8 bit, Red: 8 bit, Green: 8 bit, Blue: 8 bit*/\n")
    parts.extend(l + "\n" for l in emit_rows(d32, ""))
    parts.append("#endif\n")

    parts.append("};\n\n")
    parts.append(
        """const lv_img_dsc_t img_app_print = {
  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,
  .header.always_zero = 0,
  .header.reserved = 0,
  .header.w = 112,
  .header.h = 112,
  .data_size = 12544 * LV_IMG_PX_SIZE_ALPHA_BYTE,
  .data = img_app_print_map,
};
"""
    )

    out.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {out} from {png} ({out.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
