/* SPDX-License-Identifier: Apache-2.0 */
/* Auto-generated by gen_boot_assets.py — do not edit. */
#pragma once

#include "lvgl.h"

#define BOOT_PIN_COUNT      20
#define BOOT_CHIP_NOMINAL_W 102
#define BOOT_CHIP_NOMINAL_H 118

/* Order: top x5, bottom x5, left x5, right x5 */
static const lv_coord_t boot_pin_pos_nominal[BOOT_PIN_COUNT][2] = {
    {32, 8},
    {42, 8},
    {52, 10},
    {62, 10},
    {73, 10},
    {32, 108},
    {42, 108},
    {52, 108},
    {62, 108},
    {73, 108},
    {8, 30},
    {8, 42},
    {8, 56},
    {8, 68},
    {8, 80},
    {96, 30},
    {96, 42},
    {96, 56},
    {96, 68},
    {96, 80},
};
