#!/usr/bin/env python3
"""Generate UTF-8 codepoint -> GBK map for escpos_text_print (from lv_font_ui_zh symbols)."""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SYMBOL_DIRS = [ROOT / "components" / "lv_font_ui_zh"]
OUT = ROOT / "components" / "usb_escpos_printer" / "utf8_gbk_map.inc"

# Extra chars for print labels / punctuation
EXTRA = (
    "【】仅题目含答案步骤解析译文原文说明标题要点关键词批改结果每日一句易错提醒考点分步讲解打印失败无打印机"
    "—–…·《》「」"
)


def collect_chars() -> set[str]:
    chars: set[str] = set(EXTRA)
    for d in SYMBOL_DIRS:
        for p in sorted(d.glob("symbols*.txt")):
            for line in p.read_text(encoding="utf-8").splitlines():
                chars.update(line.strip())
    return chars


def main() -> int:
    entries: list[tuple[int, int]] = []
    for ch in sorted(chars := collect_chars()):
        try:
            gbk = ch.encode("gbk")
        except UnicodeEncodeError:
            continue
        if len(gbk) != 2:
            continue
        cp = ord(ch)
        val = gbk[0] << 8 | gbk[1]
        entries.append((cp, val))

    entries.sort(key=lambda x: x[0])
    lines = [
        "/* Auto-generated by tools/gen_utf8_gbk_table.py — do not edit. */",
        f"/* Entries: {len(entries)} */",
        "static const struct { uint32_t cp; uint16_t gbk; } s_utf8_gbk_map[] = {",
    ]
    for cp, gbk in entries:
        lines.append(f"    {{ 0x{cp:04X}u, 0x{gbk:04X}u }},")
    lines.append("};")
    lines.append(f"static const size_t s_utf8_gbk_map_len = {len(entries)};")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(entries)} entries, {len(chars)} input chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
