#!/usr/bin/env python3
# 按 lv_font_ui_zh 字集生成 ParentChat 简体拼音词库（lv_pinyin_dict_t）
import os, re, sys, urllib.request

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
FONT_DIR = os.path.join(ROOT, "components", "lv_font_ui_zh")
CACHE = os.path.join(os.path.dirname(__file__), "pinyin_data_kMandarin_8105.txt")
PINYIN_URL = "https://raw.githubusercontent.com/mozillazg/pinyin-data/master/kMandarin_8105.txt"
OUT_C = os.path.join(ROOT, "components", "apps", "parent_chat", "parent_chat_pinyin_dict.c")
OUT_H = os.path.join(ROOT, "components", "apps", "parent_chat", "parent_chat_pinyin_dict.h")
SYMBOL_FILES = ("symbols.txt", "symbols_math.txt", "symbols_extra.txt", "symbols_hans_common.txt")
MAX_PER_SYLLABLE = 12
_U_RE = re.compile(r"U\+([0-9A-F]+):\s*([^#]+)")
_ACCENT = str.maketrans({
    "ā": "a", "á": "a", "ǎ": "a", "à": "a",
    "ē": "e", "é": "e", "ě": "e", "è": "e",
    "ī": "i", "í": "i", "ǐ": "i", "ì": "i",
    "ō": "o", "ó": "o", "ǒ": "o", "ò": "o",
    "ū": "u", "ú": "u", "ǔ": "u", "ù": "u",
    "ǖ": "v", "ǘ": "v", "ǚ": "v", "ǜ": "v", "ü": "v",
})

def load_han_order():
    seen, out = set(), []
    for name in SYMBOL_FILES:
        path = os.path.join(FONT_DIR, name)
        if not os.path.isfile(path):
            continue
        for line in open(path, encoding="utf-8"):
            s = line.strip()
            if not s or s.startswith("#"):
                continue
            for ch in s:
                if ord(ch) < 0x80 or ch in seen:
                    continue
                seen.add(ch)
                out.append(ch)
    return out

def toneless(py):
    return py.strip().lower().translate(_ACCENT).rstrip("12345")

def fetch_pinyin_table():
    if not os.path.isfile(CACHE):
        print("download", PINYIN_URL, file=sys.stderr)
        with urllib.request.urlopen(PINYIN_URL, timeout=60) as r:
            open(CACHE, "wb").write(r.read())
    table = {}
    for line in open(CACHE, encoding="utf-8"):
        m = _U_RE.match(line.strip())
        if not m:
            continue
        ch = chr(int(m.group(1), 16))
        pys = [toneless(x) for x in m.group(2).split(",") if x.strip()]
        if pys:
            table[ch] = pys
    return table

def build_dict(han_list, table):
    rank = {ch: i for i, ch in enumerate(han_list)}
    groups = {}
    for ch in han_list:
        for py in table.get(ch, []):
            if py and py[0].isalpha():
                groups.setdefault(py, set()).add(ch)
    items = []
    for py in sorted(groups.keys()):
        chars = sorted(groups[py], key=lambda c: rank.get(c, 99999))[:MAX_PER_SYLLABLE]
        if chars:
            items.append((py, "".join(chars)))
    return items

def c_escape(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

def write_outputs(items):
    lines_c = [
        "/* auto-generated by tools/gen_parent_chat_pinyin_dict.py — do not edit */",
        '#include "parent_chat_pinyin_dict.h"',
        "#if LV_USE_IME_PINYIN",
        "const lv_pinyin_dict_t parent_chat_pinyin_dict[] = {",
    ]
    for py, mb in items:
        lines_c.append(f'    {{ "{c_escape(py)}", "{c_escape(mb)}" }},')
    lines_c += ["    { NULL, NULL }", "};", "#endif", ""]
    open(OUT_C, "w", encoding="utf-8", newline="\n").write("\n".join(lines_c))
    open(OUT_H, "w", encoding="utf-8", newline="\n").write(
        "/* auto-generated by tools/gen_parent_chat_pinyin_dict.py */\n"
        "#pragma once\n#include \"lvgl.h\"\n"
        "#if LV_USE_IME_PINYIN\n"
        "extern const lv_pinyin_dict_t parent_chat_pinyin_dict[];\n"
        "#endif\n"
    )

def main():
    han = load_han_order()
    if not han:
        print("no han chars", file=sys.stderr)
        return 1
    table = fetch_pinyin_table()
    items = build_dict(han, table)
    write_outputs(items)
    mb_bytes = sum(len(mb.encode("utf-8")) for _, mb in items)
    print(f"syllables={len(items)} han={len(han)} mb_rodata~={mb_bytes}B -> {OUT_C}", file=sys.stderr)
    return 0

if __name__ == "__main__":
    sys.exit(main())
