#!/usr/bin/env python3
"""Generate LVGL C image assets for boot splash (RGB565 + alpha, 16-bit)."""
from __future__ import annotations

import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Pillow required: pip install Pillow", file=sys.stderr)
    sys.exit(1)

WHITE_TRIM_MIN = 248
MAX_LOGO_W = 920
CHIP_FALLBACK_FRAC = 0.17
# Nudge split left so "AI赋能设计..." stays entirely in the text strip (A was clipped).
SPLIT_SHIFT_LEFT_PX = 26


def rgb_to_lv16(r: int, g: int, b: int) -> int:
    b5 = (b >> 3) & 0x1F
    g6 = (g >> 2) & 0x3F
    r5 = (r >> 3) & 0x1F
    return b5 | (g6 << 5) | (r5 << 11)


def emit_rows(bytes_list: list[int], first_line_comment: str) -> list[str]:
    lines: list[str] = []
    n = len(bytes_list)
    i = 0
    while i < n:
        chunk = bytes_list[i : i + 16]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        if i == 0 and first_line_comment:
            lines.append(f"  /*{first_line_comment}*/\n  {hexes},")
        else:
            lines.append(f"  {hexes},")
        i += 16
    return lines


def is_content_pixel(r: int, g: int, b: int, a: int) -> bool:
    if a < 12:
        return False
    return not (r >= WHITE_TRIM_MIN and g >= WHITE_TRIM_MIN and b >= WHITE_TRIM_MIN)


def trim_near_white_border(im: Image.Image) -> Image.Image:
    im = im.convert("RGBA")
    w, h = im.size
    px = im.load()

    min_x, min_y = w, h
    max_x, max_y = -1, -1
    for y in range(h):
        for x in range(w):
            if is_content_pixel(*px[x, y]):
                min_x = min(min_x, x)
                min_y = min(min_y, y)
                max_x = max(max_x, x)
                max_y = max(max_y, y)

    if max_x < min_x or max_y < min_y:
        return im
    pad = 2
    min_x = max(0, min_x - pad)
    min_y = max(0, min_y - pad)
    max_x = min(w - 1, max_x + pad)
    max_y = min(h - 1, max_y + pad)
    return im.crop((min_x, min_y, max_x + 1, max_y + 1))


def column_ink_count(im: Image.Image) -> list[int]:
    im = im.convert("RGBA")
    w, h = im.size
    px = im.load()
    counts: list[int] = []
    for x in range(w):
        n = 0
        for y in range(h):
            if is_content_pixel(*px[x, y]):
                n += 1
        counts.append(n)
    return counts


def find_chip_text_split_x(im: Image.Image) -> int:
    """
    The chip icon is roughly square (width ~ height). Find the lowest-ink column
    just to the right of that width — the narrow gap before 'AI赋能设计...'.
    """
    w, h = im.size
    counts = column_ink_count(im)
    if not counts:
        return max(1, int(w * CHIP_FALLBACK_FRAC))

    search_lo = max(1, int(h * 0.92))
    search_hi = min(w - 2, int(h * 1.08))

    best_x = search_lo
    best_c = counts[search_lo]
    for x in range(search_lo, search_hi + 1):
        if counts[x] < best_c:
            best_c = counts[x]
            best_x = x

    split_x = best_x + 1 - SPLIT_SHIFT_LEFT_PX
    split_x = max(int(h * 0.82), min(split_x, w - 1))
    print(
        f"  split_x={split_x} / {w} ({100.0 * split_x / w:.1f}%), h={h}, "
        f"gap@{best_x}, shift_left={SPLIT_SHIFT_LEFT_PX}"
    )
    return split_x


def scale_to_max_width(im: Image.Image, max_w: int) -> Image.Image:
    w, h = im.size
    if w <= max_w:
        return im
    nh = max(1, int(round(h * max_w / w)))
    return im.resize((max_w, nh), Image.Resampling.LANCZOS)


def rgba_to_lv16_bytes(im: Image.Image) -> tuple[list[int], int, int]:
    im = im.convert("RGBA")
    w, h = im.size
    out: list[int] = []
    for r, g, b, a in im.getdata():
        v = rgb_to_lv16(r, g, b)
        lo, hi = v & 0xFF, (v >> 8) & 0xFF
        out.extend([lo, hi, a])
    return out, w, h


def write_c_array(out_path: Path, sym: str, im: Image.Image, src_name: str) -> None:
    d16, w, h = rgba_to_lv16_bytes(im)
    attr = f"LV_ATTRIBUTE_IMG_{sym.upper()}"
    parts = [
        "/* SPDX-License-Identifier: Apache-2.0 */\n",
        f"/* Generated by gen_boot_assets.py from {src_name} */\n\n",
        "#ifdef __has_include\n",
        "    #if __has_include(\"lvgl.h\")\n",
        "        #ifndef LV_LVGL_H_INCLUDE_SIMPLE\n",
        "            #define LV_LVGL_H_INCLUDE_SIMPLE\n",
        "        #endif\n",
        "    #endif\n",
        "#endif\n\n",
        "#if defined(LV_LVGL_H_INCLUDE_SIMPLE)\n",
        "    #include \"lvgl.h\"\n",
        "#else\n",
        "    #include \"lvgl/lvgl.h\"\n",
        "#endif\n\n",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN\n",
        "#define LV_ATTRIBUTE_MEM_ALIGN\n",
        "#endif\n\n",
        f"#ifndef {attr}\n",
        f"#define {attr}\n",
        "#endif\n\n",
        f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST {attr} uint8_t {sym}_map[] = {{\n",
        "#if LV_COLOR_DEPTH == 16 && LV_COLOR_16_SWAP == 0\n",
        "  /*Pixel format: Alpha 8 bit, RGB565*/\n",
    ]
    parts.extend(l + "\n" for l in emit_rows(d16, f"{w}x{h}"))
    parts.append("#endif\n};\n\n")
    parts.append(
        f"const lv_img_dsc_t {sym} = {{\n"
        "  .header.cf = LV_IMG_CF_TRUE_COLOR_ALPHA,\n"
        "  .header.always_zero = 0,\n"
        "  .header.reserved = 0,\n"
        f"  .header.w = {w},\n"
        f"  .header.h = {h},\n"
        f"  .data_size = {w * h} * LV_IMG_PX_SIZE_ALPHA_BYTE,\n"
        f"  .data = {sym}_map,\n"
        "};\n"
    )
    out_path.write_text("".join(parts), encoding="utf-8")
    print(f"Wrote {out_path} ({w}x{h}, {out_path.stat().st_size} bytes)")


def detect_pin_centers(chip: Image.Image) -> list[tuple[int, int]]:
    """Return 20 pin-tip centers: top5, bottom5, left5, right5."""
    w, h = chip.size
    px = chip.convert("RGBA").load()

    def is_pin(r: int, g: int, b: int, a: int) -> bool:
        if a < 128:
            return False
        return r < 100 and g < 120 and b < 160 and (r + g + b) < 280

    tips: list[tuple[int, int]] = []
    for y in range(h):
        for x in range(w):
            if not is_pin(*px[x, y]):
                continue
            if not (y < 14 or y > h - 14 or x < 14 or x > w - 14):
                continue
            n = 0
            for dx in (-1, 0, 1):
                for dy in (-1, 0, 1):
                    if dx == 0 and dy == 0:
                        continue
                    nx, ny = x + dx, y + dy
                    if 0 <= nx < w and 0 <= ny < h and is_pin(*px[nx, ny]):
                        n += 1
            if n <= 4:
                tips.append((x, y))

    def cluster(pts: list[tuple[int, int]], axis: int, tol: int = 6) -> list[tuple[int, int]]:
        pts = sorted(pts, key=lambda p: p[axis])
        groups: list[list[tuple[int, int]]] = []
        for p in pts:
            if not groups or abs(p[axis] - groups[-1][0][axis]) > tol:
                groups.append([p])
            else:
                groups[-1].append(p)
        out: list[tuple[int, int]] = []
        for g in groups:
            cx = round(sum(p[0] for p in g) / len(g))
            cy = round(sum(p[1] for p in g) / len(g))
            out.append((cx, cy))
        return out

    top = cluster([(x, y) for x, y in tips if y < 14], 0)
    bot = cluster([(x, y) for x, y in tips if y > h - 14], 0)
    lef = cluster([(x, y) for x, y in tips if x < 14], 1)
    rig = cluster([(x, y) for x, y in tips if x > w - 14], 1)
    return top + bot + lef + rig


def write_pin_coords_header(path: Path, chip: Image.Image) -> None:
    pins = detect_pin_centers(chip)
    w, h = chip.size
    lines = [
        "/* SPDX-License-Identifier: Apache-2.0 */\n",
        "/* Auto-generated by gen_boot_assets.py — do not edit. */\n",
        "#pragma once\n\n",
        "#include \"lvgl.h\"\n\n",
        f"#define BOOT_PIN_COUNT      {len(pins)}\n",
        f"#define BOOT_CHIP_NOMINAL_W {w}\n",
        f"#define BOOT_CHIP_NOMINAL_H {h}\n\n",
        "/* Order: top x5, bottom x5, left x5, right x5 */\n",
        "static const lv_coord_t boot_pin_pos_nominal[BOOT_PIN_COUNT][2] = {\n",
    ]
    for i, (x, y) in enumerate(pins):
        lines.append(f"    {{{x}, {y}}},\n")
    lines.append("};\n")
    path.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {path} ({len(pins)} pins, chip {w}x{h})")


def main() -> None:
    root = Path(__file__).resolve().parent
    src = root / "boot_logo.png"
    if not src.is_file():
        print(f"Missing {src}", file=sys.stderr)
        sys.exit(1)

    logo = trim_near_white_border(Image.open(src))
    logo = scale_to_max_width(logo, MAX_LOGO_W)

    lw, lh = logo.size
    split_x = find_chip_text_split_x(logo)
    chip = logo.crop((0, 0, split_x, lh))
    text = logo.crop((split_x, 0, lw, lh))
    text = trim_near_white_border(text)

    write_c_array(root / "img_boot_chip.c", "img_boot_chip", chip, src.name)
    write_c_array(root / "img_boot_text.c", "img_boot_text", text, src.name)
    write_pin_coords_header(root.parent / "include" / "boot_pin_coords.h", chip)


if __name__ == "__main__":
    main()
